name: build and deploy

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monitor-api
        uses: actions/checkout@v2

      - name: Checkout common
        uses: actions/checkout@v2
        with:
          repository: 'openmonitor/common'
          path: 'common/'
          token: ${{ secrets.ZK_REPO }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: zkdev
          password: ${{ secrets.ZK_PACKAGE }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            DBHOST_ARG=localhost
            DBPORT_ARG=${{ secrets.DB_PORT }}
            DBUSER_ARG=${{ secrets.DB_USERNAME }}
            DBPASSWD_ARG=${{ secrets.DB_PASSWD }}
            DB_ARG=${{ secrets.DB }}
          context: .
          file: ./Dockerfile
          tags: |
            ghcr.io/openmonitor/monitor-api:latest
          push: true
          # used to fetch repository
          secrets: |
            GIT_AUTH_TOKEN=${{ github.token }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_TARGET }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSWD }}
          script: |
            sudo docker login https://ghcr.io -u zkdev --password ${{ secrets.ZK_PACKAGE }}
            sudo docker stop openmonitor-monitor-api
            sudo docker rm openmonitor-monitor-api
            sudo docker pull ghcr.io/openmonitor/monitor-api:latest
            sudo docker run -dit --name openmonitor-monitor-api --net host ghcr.io/openmonitor/monitor-api:latest

